const products = [
    {
      id: 0,
      name: "Spaghetti",
      price: 55.00,
      instock: 15,
      imgSrc: "../assets/Spag.jpeg",
    },
    {
      id: 1,
      name: "Tuna Carbonara",
      price: 55.00,
      instock: 15,
      imgSrc: "../assets/TC.jpeg",
    },
    {
      id: 2,
      name: "Tuna Aglio Olio",
      price: 55.00,
      instock: 15,
      imgSrc: "../assets/TunaAglioOlio.jpeg",
    },
    {
        id: 3,
        name: "Pork Tonkatsu",
        price: 99.00,
        instock: 15,
        imgSrc: "../assets/Tonkatsu.jpeg",
    },
    {
        id: 4,
        name: "Chicken Popper",
        price: 89.00,
        instock: 15,
        imgSrc: "../assets/CP.jpeg",
    },
    {
        id: 5,
        name: "Palitaw",
        price: 60.00,
        instock: 15,
        imgSrc: "../assets/Palitaw.jpeg",
    },
    {
        id: 6,
        name: "Butchi",
        price: 60.00,
        instock: 15,
        imgSrc: "../assets/Butchi.jpeg",
    },
]